### ISSUE TITLE
Scrum Reports July 30

### ISSUE THREAD

**Issue by royroyzhong** [IsabellaLCYang/Simp.Com#140]

**Comment by royroyzhong** [comment]
Ruming (Roy) Zhong

I completed all the live chat features, added and redesigned some UI, updated some authentication warming and logic, adding the search function in the order page in buyer view. In the last iteration, the live chat logic and making the UI takes me lots of time since the message data are not stored in the database. Since we don't have many meaningful data in our database, I will make some meaningful data and collect some images for that. And also, I will improve the UI to be responsive.

**Comment by Gavinygh** [comment]
Guanghua Yang n5l3b

I created a cache for the cart part to make the products persistent, which means what you have in the cart won't be lost once you refresh the page.  In addition, I changed the schema of "order" and "product" on the server side and deleted orderSlice on the front end, which aims to avoid storing redundant data. The most challenging part would be changing the corresponding parts on both the front end and routes that relate to the data structure I changed. In the next progress, I will finish the seller summary page and keep testing to find bugs.

**Comment by IsabellaLCYang** [comment]
Isabella Yang m9e3b

I implemented the drag and drop as well as image display for the products. In this way, sellers can upload product images and buyers can see the gallery of automatic playing images for products that they're interested in.  The most challenging part is learning how to use the external libraries through their documentation. As we approach the end of the course, I will be cleaning up and fixing all the cart-related pages and actions to ensure flawless interaction. In addition, I will be implementing a wishlist feature which enables users to get email notifications if they wanted items are restocked.

**Comment by t-quinn-t** [comment]
Quinn Tao y3z2b

I built the image related backend functionality on top of Isabella's drag and drop features. Also, I finished product schema. That said, there is still a bit functionality I need to finish(delete product etc), so I have to work on that this week. Also, the image schema needs a bit change as currently the size of the RESTful requests is too big.
