### ISSUE TITLE
Biweekly Scrum July 16

### ISSUE THREAD

**Issue by royroyzhong** [IsabellaLCYang/Simp.Com#98]

**Comment by royroyzhong** [comment]
Ruming(Roy) Zhong

I implemented all the login/sign-up APIs in the past iteration and created the buyer and seller schema. Adding Salt and encrypted password for user sign up before saving in database. For the login functionality, I set up the web cookie, opened cores for the frontend, added an error message for each event, and finished logging in with a google account. Lastly, I started with the live chat stretch requirements, at this point, the frontend has its UI and the backend started using socket.io to communicate. I feel like adding the UI for live chat is not easy at this point since there is not much space left on the website but it is doable. I will complete the integration of all the live chat features, put data into the database, and help other parts if needed.

**Comment by IsabellaLCYang** [comment]
Isabella (Lichuan) Yang

In the past two weeks, I finished the implementation of submitting an order from cart to our database as well as reflecting such addition of order on the seller side dashboard. Furthermore, I added the feature allowing seller to update the status of an order and such changes will be reflected in our database as well. The challenges I encountered the most has to do with parsing json and I got many syntax errors while trying to make request to backend to retrieve response from there. In the upcoming weeks, I will shift my focus to email notifications. I think the ocordination between waiting for trigger to sne d the emial notification and the actual sending of the email might be challenging, but I will look at some documentations to find a way to resolve issues.

**Comment by Gavinygh** [comment]
Gavin (Guanghua) Yang

In the past two weeks, I did the part of loading products from database and display them in frontend for the customer to review. As well, I finished adding products to cart, and updating quantity of products in cart. The major challenge I encountered was modifying the data structure in the progress of adding functionality. In the next project progress, my task will mainly focus on designing a cache for cart, and extract the summary data from database to display in the seller summary page.

**Comment by t-quinn-t** [comment]
Qintu (Quinn) Tao

In the past two weeks, I finished backend integration of the product system. Including seller adding products and modifying details of a particular product, which involved some API and DB. For the next iteration, I am going to work on the image upload/ drag and drop feature. Also, I am going to write the product view page for buyers.
